x-logging:
  &default-logging
  options:
    max-size: "100k"
    max-file: "5"
  driver: json-file

services:
  traefik:
    image: traefik:latest
    logging: *default-logging
    labels:
      - traefik.enable=${TRAEFIK_API_ENABLE:-false}
      - traefik.http.middlewares.api-auth.basicauth.users=${TRAEFIK_API_BASIC_AUTH_USERS:-}
      - traefik.http.routers.api.middlewares=api-auth
      - traefik.http.routers.api.rule=Host(`traefik.${CF_DOMAIN}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.services.api.loadBalancer.server.port=80 # dummy port required in host mode
    environment:
      CF_API_KEY: ${CF_API_TOKEN}
      CF_API_EMAIL: ${CF_API_EMAIL}
    command:
      # act as a reverse proxy for docker containers with label "traefik.enable=true"
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      # enable stdout access log
      - --accessLog=true
      # enable traefik dashboard
      - --api.dashboard=${TRAEFIK_API_ENABLE:-false}
      # listen addresses
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      # trust cloudflare forwarded headers (https://www.cloudflare.com/ips-v4)
      - --entryPoints.web.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      # redirect http to https
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      # configure letsencrypt acme
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.letsencrypt.acme.email=${CF_API_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
      # configure letsencrypt default certificate
      - --entryPoints.websecure.http.tls.certResolver=letsencrypt
      - --entryPoints.websecure.http.tls.domains[0].main=${CF_DOMAIN}
      - --entryPoints.websecure.http.tls.domains[0].sans=*.${CF_DOMAIN}
      # trust insecure certificates
      - --serversTransport.insecureSkipVerify=true
      # opt out of usage statistics
      - --global.sendAnonymousUsage=false
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/acme:/etc/traefik/acme
    restart: unless-stopped

  cloudflare:
    image: tiredofit/traefik-cloudflare-companion
    logging: *default-logging
    environment:
      CONTAINER_ENABLE_MONITORING: "false"
      CF_EMAIL: ${CF_API_EMAIL}
      CF_TOKEN: ${CF_API_TOKEN}
      DOMAIN1: ${CF_DOMAIN}
      DOMAIN1_PROXIED: ${CF_DOMAIN_PROXIED:-true}
      DOMAIN1_ZONE_ID: ${CF_ZONE_ID}
      TARGET_DOMAIN: ${CF_TARGET:-CF_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - traefik
    restart: unless-stopped
